apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: adservice-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       adservice
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: server
      minAllowed:
        cpu: 50m
        memory: 50Mi
      maxAllowed:
        cpu: 300m
        memory: 300Mi
      controlledResources: ["cpu", "memory"]
