apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cartservice-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       cartservice
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: server
      minAllowed:
        cpu: 100m
        memory: 32Mi
      maxAllowed:
        cpu: 300m
        memory: 128Mi
      controlledResources: ["cpu", "memory"]
