apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: productcatalogservice-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       productcatalogservice
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
    - containerName: server
      minAllowed:
        cpu: 50m
        memory: 32Mi
      maxAllowed:
        cpu: 200m
        memory: 128Mi
      controlledResources: ["cpu", "memory"]
